
name: 'dbt_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'dbt_ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_ecommerce:
    staging:
      +materialized: view
      +snowflake_warehouse: ecommerce_wh
    intermediate:
      +materialized: table
      +snowflake_warehouse: ecommerce_wh
    marts:
      +materialized: table
      +snowflake_warehouse: ecommerce_wh
